# Generated by Django 4.1 on 2025-02-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='kind',
            field=models.SmallIntegerField(choices=[(None, 'Выберите тип публикуемого объявления'), (1, 'Покупка'), (2, 'Продажа'), (3, 'Обмен'), (4, 'Аренда')], default='Выберите тип публикуемого объявления'),
        ),
    ]
