# Generated by Django 4.1 on 2025-01-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0002_category_alter_billboard_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billboard',
            old_name='pubric_id',
            new_name='category_id',
        ),
    ]
