# Generated by Django 5.1.6 on 2025-02-12 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0002_alter_billboard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='image',
            field=models.ImageField(blank=True, default='images/billboard.jpg', error_messages={'invalid_extension': 'Этот формат не поддерживается'}, upload_to='images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png', 'jpeg'))], verbose_name='Изображение'),
        ),
    ]
