# Generated by Django 4.1 on 2025-01-31 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0003_rename_pubric_id_billboard_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billboard',
            old_name='category_id',
            new_name='category',
        ),
    ]
