# Generated by Django 4.1 on 2025-02-07 08:01

import billboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0003_alter_billboard_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='', verbose_name='Описание категории'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billboard',
            name='price',
            field=models.FloatField(validators=[billboard.validators.validate_price], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='title',
            field=models.CharField(max_length=50, validators=[billboard.validators.validate_title], verbose_name='Объявление'),
        ),
    ]
