# Generated by Django 4.1 on 2025-01-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billboard',
            options={'ordering': ['category__name', '-published_at'], 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.SlugField(unique=True, verbose_name='Название'),
        ),
    ]
