# Generated by Django 5.1.6 on 2025-02-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
