# Generated by Django 5.1.6 on 2025-02-08 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0007_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='image',
            field=models.ImageField(default='static_dev/img/no_content.jpg', error_messages={'invalid_extension': 'Этот формат не поддерживается'}, upload_to='images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png', 'jpeg'))], verbose_name='Изображение'),
        ),
    ]
